ProjetoFinal/ProjetoFinal/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoFinal.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: CategoriesController
        public ActionResult Categories()
        {
            Categories categoria = new Categories();

            List<Categories> jsonInfo = categoria.GetJsonInfo();

            ViewBag.info = jsonInfo;

            return View();
        }

        // GET: CategoriesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CategoriesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoriesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoriesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CategoriesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoriesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CategoriesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetoFinal/ProjetoFinal/Controllers/ConteudosController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjetoFinal.Controllers
{
    public class ConteudosController : Controller
    {
        public IActionResult Materias()
        {
            return View();
        }

        public IActionResult Podcasts()
        {
            return View();
        }
    }
}

ProjetoFinal/ProjetoFinal/Controllers/ContratarController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoFinal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoFinal.Controllers
{
    public class ContratarController : Controller
    {
        // GET: ContratarController
        public ActionResult Index()
        {
            Contratar cardInfo = new Contratar();

            List<Contratar> info = cardInfo.getCardInfo();

            ViewBag.info = info;

            return View();
        }

        // GET: ContratarController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ContratarController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContratarController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ContratarController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ContratarController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ContratarController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ContratarController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ProjetoFinal/ProjetoFinal/Controllers/TalentosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoFinal.Data;
using ProjetoFinal.Models;

namespace ProjetoFinal.Controllers
{
    public class TalentosController : Controller
    {
        private readonly ProjetoFinalContext _context;
        private readonly IWebHostEnvironment _hostEnviroment;

        public TalentosController(ProjetoFinalContext context, IWebHostEnvironment hostEnviroment)
        {
            _context = context;
            this._hostEnviroment = hostEnviroment;
        }

        // GET: Talentoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Talento.ToListAsync());
        }

        public async Task<IActionResult> ShowTalents(string area)
        {
            ViewData["Categoria"] = area;

            return View(await _context.Talento.Where(item => item.Profissao.Contains(area)).ToListAsync());
        }


        /*
        public string ShowTalentos(string area)
        {
            return "passando >> " + area;
        }*/


        // GET: Talentoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var talento = await _context.Talento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (talento == null)
            {
                return NotFound();
            }

            return View(talento);
        }

        // GET: Talentoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Talentoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Imagem, Nome, Localidade, Sobre, Profissao, Email, Telefone, Formacao, Local1, Funcao1, Atividade1, Local2, Funcao2, Atividade2, Instituicao1, CargaHoraria1, Instituicao2, CargaHoraria2, Aprendeu, Habilidades, Area, Nivel")] Talento talento)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnviroment.WebRootPath;

                string fileName = Path.GetFileNameWithoutExtension(talento.Imagem.FileName);
                string extension = Path.GetExtension(talento.Imagem.FileName);
                string newFileName = string.Format("{0}{1}{2}", fileName, DateTime.Now.ToString("yymmssfff"), extension);

                talento.ImagemNome = newFileName;

                string path = Path.Combine(string.Format("{0}/img/userImage", wwwRootPath), newFileName);

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await talento.Imagem.CopyToAsync(fileStream);
                }

                _context.Add(talento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));
            }
            return View(talento);
        }

        // GET: Talentoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var talento = await _context.Talento.FindAsync(id);
            if (talento == null)
            {
                return NotFound();
            }
            return View(talento);
        }

        // POST: Talentoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Imagem,Nome,Cidade,Estado,Bio,Profissao,Email,Telefone,Area,Nivel")] Talento talento)
        {
            if (id != talento.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(talento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TalentoExists(talento.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(talento);
        }

        // GET: Talentoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var talento = await _context.Talento
                .FirstOrDefaultAsync(m => m.Id == id);
            if (talento == null)
            {
                return NotFound();
            }

            return View(talento);
        }

        // POST: Talentoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var talento = await _context.Talento.FindAsync(id);
            _context.Talento.Remove(talento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TalentoExists(int id)
        {
            return _context.Talento.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Areas()
        {
            return View(await _context.Talento.ToListAsync());
        }
    }
}

ProjetoFinal/ProjetoFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BCB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/home.css" />
    <link rel="stylesheet" href="~/css/materias.css" />
    <link rel="stylesheet" href="~/css/header_footer.css" />
    <link rel="stylesheet" href="~/css/cadastrar.css" />
    <link rel="stylesheet" href="~/css/info.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
</head>
<body>
    <header class="cor-fundo-header-footer">
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-dark box-shadow cor-fundo-header-footer">
            <div class="container-fluid link-header-footer">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="logo-header" src="~/img/logo/logo-completa.png" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex flex-md-row-reverse">
                    <ul class="navbar-nav flex-grow-1 ">
                        <li class="nav-item texto-header">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><span class="cor-secundaria-texto hover-link">Home</span></a>
                        </li>
                        <li>
                            <div class="dropdown hover-link">
                                <button id="botao-menu" type="button" class="btn btn-link cor-secundaria-texto texto-header hover-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-decoration: none;">
                                    Conteúdos
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="background-color: #C4C4C4;">
                                    <a class="nav-link hover-link" asp-area="" asp-controller="Conteudos" asp-action="Materias">Matérias</a>
                                    <a class="nav-link hover-link" asp-area="" asp-controller="Conteudos" asp-action="Podcasts">Podcasts</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item texto-header hover-link">
                            <a class="nav-link" asp-area="" asp-controller="Contratar" asp-action="Index"><span class="cor-secundaria-texto hover-link">Contratar</span></a>
                        </li>
                        <li class="nav-item texto-header hover-link">
                            <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Categories"><span class="cor-secundaria-texto hover-link">Talentos</span></a>
                        </li>
                        <li class="nav-item texto-header hover-link">
                            <a class="nav-link" asp-area="" asp-controller="Talentos" asp-action="Create"><span class="cor-secundaria-texto hover-link">Cadastre-se</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div><!--class="container"-->
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <footer id="foot" class="footer text-muted" style="margin-bottom: -10%; border-top: 2px solid #FFD79C;">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6 col-lg-6 my-2 cor-secundaria-texto d-lg-flex flex-lg-column align-items-lg-center">
                    <h3 class="titulo-terciario mt-3 ml-2 ml-lg-5 pt-5">Links Rápidos</h3>
                    <ul class="texto-terciario link-header-footer">
                        <li>
                            <a class="nav-link hover-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <div class="btn-group dropright hover-link">
                                <button type="button" class="btn btn-link cor-secundaria-texto texto-terciario hover-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-decoration: none;">
                                    Conteúdos
                                </button>
                                <div class="dropdown-menu" style="background-color: #C4C4C4;">
                                    <a class="nav-link hover-link" asp-area="" asp-controller="Conteudos" asp-action="Materias">Matérias</a>
                                    <a class="nav-link hover-link" asp-area="" asp-controller="Conteudos" asp-action="Podcasts">Podcasts</a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <a class="nav-link hover-link" asp-area="" asp-controller="Contratar" asp-action="Index">Contratar</a>
                        </li>
                        <li>
                            <a class="nav-link hover-link" asp-area="" asp-controller="Categories" asp-action="Categories">Talentos</a>
                        </li>
                        <li>
                            <a class="nav-link hover-link" asp-area="" asp-controller="Talentos" asp-action="Create">Cadastre-se</a>
                        </li>
                    </ul>
                </div>
                
                <div class="col-sm-12 col-md-6 col-lg-6 my-2 cor-secundaria-texto d-lg-flex flex-lg-column align-items-lg-center">
                    <h3 class="mx-3 titulo-terciario pt-5">Redes Sociais</h3>
                    <ul class="texto-terciario link-header-footer ml-3">
                        <li class="hover-link mt-4 mt-sm-3 mt-md-0 mt-lg-2 fab fa-github-square">
                            <a href="" target="_blank" class="hover-link texto-terciario" style="text-decoration: none;">&nbspGitHub do Projeto</a>
                        </li><br>
                        <li class="my-2 hover-link fab fa-facebook-square">
                            <span class="texto-terciario">&nbspFacebook</span>
                        </li><br>
                        <li class="mb-3 hover-link fab fa-twitter-square">
                            <span class="texto-terciario">&nbspTwitter</span>
                        </li><br>
                        <li class="mb-3 hover-link fab fa-instagram">
                            <span class="texto-terciario">&nbspInstagram</span>
                        </li><br>
                        <li class="hover-link fab fa-linkedin">
                            <span class="texto-terciario">&nbspLinkedin</span>
                        </li>
                    </ul>
                </div>
            </div>

            <p class="borda-footer">.</p>

            <div class="row">
                <div class="col-12 d-flex justify-content-center mt-3">
                    <img src="~/img/logo/logo-completa.png" class="logo-header" alt="">
                </div>
                <div class="col-12 d-flex justify-content-center texto-footer cor-secundaria">
                    <p>&copy; 2022 - BLACK CODE BRASIl - sq58.recodepro@gmail.com</p>                     
                </div>
                <div class="col-12 d-flex justify-content-center texto-footer cor-secundaria">
                   <a class="nav-link hover-link" asp-area="" asp-controller="Talentos" asp-action="Index">Administrador</a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>